services:
  - type: web
    name: truevesti-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: EMAIL_PROVIDER
        value: resend
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CRYPTO_PROVIDER
        value: mock
    healthCheckPath: /health